src/Iti/BlogBundle/Form/PostType.php
<?php

namespace Iti\BlogBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('content')
            ->add('createdAt')
            ->add('image')
            ->add('category')
            ->add('tags')
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Iti\BlogBundle\Entity\Post'
        ));
    }

    public function getName()
    {
        return 'iti_blogbundle_posttype';
    }
}

src/Iti/BlogBundle/Controller/BlogController.php
<?php

namespace Iti\BlogBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;

class BlogController extends Controller {
    
    public function sideBarAction(){
        
        return $this->render('ItiBlogBundle:Blog:sideBar.html.twig', array(
                    
                ));
    }

    /**
     * this function used to show tag posts
     * @author ahmed
     * @param integer $id
     * @param integer $page
     */
    public function tagsAction($id, $page) {
        $em = $this->getDoctrine()->getEntityManager();
        $postRepo = $em->getRepository('ItiBlogBundle:Post');
        $tagRepo = $em->getRepository('ItiBlogBundle:Tag');

        $tag = $tagRepo->find($id);

        if (!$tag) {
            throw $this->createNotFoundException('Unable to find this tag.');
        }

        $itemsPerPage = $this->container->getParameter('posts_per_page');

        $posts = $postRepo->getTagPosts($id, $page, $itemsPerPage);
        foreach ($posts as $post) {
            if (strlen($post->getContent()) > 150)
                $post->setContent(substr($post->getContent(), 0, 150) . '....');
        }

        $postsCount = $postRepo->countTagPosts($id);
        $postsCount = $postsCount['0']['postsCount'];

        //calculate the last page number
        $lastPageNumber = (int) ($postsCount / $itemsPerPage);
        if (($postsCount % $itemsPerPage) > 0) {
            $lastPageNumber++;
        }

        return $this->render('ItiBlogBundle:Blog:tag.html.twig', array(
                    'tag' => $tag,
                    'id' => $id,
                    'posts' => $posts,
                    'page' => $page,
                    'lastPageNumber' => $lastPageNumber
                ));
    }

    /**
     * this function used to show category posts
     * @author ahmed
     * @param integer $id
     * @param integer $page
     */
    public function categoryAction($id, $page) {
        $em = $this->getDoctrine()->getEntityManager();
        $postRepo = $em->getRepository('ItiBlogBundle:Post');
        $categoryRepo = $em->getRepository('ItiBlogBundle:Category');

        $category = $categoryRepo->find($id);

        if (!$category) {
            throw $this->createNotFoundException('Unable to find this category.');
        }

        $itemsPerPage = $this->container->getParameter('posts_per_page');

        $posts = $postRepo->getCategoryPosts($id, $page, $itemsPerPage);
        foreach ($posts as $post) {
            if (strlen($post->getContent()) > 150)
                $post->setContent(substr($post->getContent(), 0, 150) . '....');
        }

        $postsCount = $postRepo->countCategoryPosts($id);
        $postsCount = $postsCount['0']['postsCount'];

        //calculate the last page number
        $lastPageNumber = (int) ($postsCount / $itemsPerPage);
        if (($postsCount % $itemsPerPage) > 0) {
            $lastPageNumber++;
        }

        return $this->render('ItiBlogBundle:Blog:category.html.twig', array(
                    'category' => $category,
                    'id' => $id,
                    'posts' => $posts,
                    'page' => $page,
                    'lastPageNumber' => $lastPageNumber
                ));
    }

    /**
     * this function used to add post comment
     * @author ahmed
     * @param integer $postId
     * @param string $commentText
     */
    public function addPostCommentAction($postId, $commentText) {
        $em = $this->getDoctrine()->getEntityManager();
        $postRepo = $em->getRepository('ItiBlogBundle:Post');

        //get the post
        $post = $postRepo->find($postId);
        if ($post) {
            //create new comment
            $newComment = new \Iti\BlogBundle\Entity\Comment();
            $newComment->setComment($commentText);
            $newComment->setPost($post);

            //increment post no of comments
            $post->setNoOfComments($post->getNoOfComments() + 1);

            $em->persist($newComment);
            $em->flush();

            return $this->render('ItiBlogBundle:Blog:newComment.html.twig', array(
                        'comment' => $newComment
                    ));
        } else {
            return new Response('faild');
        }
    }

    /**
     * this function used to show home page
     * @author ahmed
     */
    public function indexAction() {
        //get latest 6 posts
        $em = $this->getDoctrine()->getEntityManager();
        $postRepo = $em->getRepository('ItiBlogBundle:Post');

        $latestPosts = $postRepo->findBy(array(), array('createdAt' => 'desc'), $limit = 6);
//        $latestPosts = $postRepo->getLatestPosts(6);
        //cut post content 
        foreach ($latestPosts as $post) {
            if (strlen($post->getContent()) > 150)
                $post->setContent(substr($post->getContent(), 0, 150) . '....');
        }

        return $this->render('ItiBlogBundle:Blog:index.html.twig', array(
                    'latestPosts' => $latestPosts
                ));
    }

    /**
     * this function used to show about page
     * @author ahmed
     */
    public function aboutUsAction() {
        return $this->render('ItiBlogBundle:Blog:aboutUs.html.twig', array(
                ));
    }

}

src/Iti/BlogBundle/Resources/views/Blog/aboutUs.html.twig
{% extends '::base.html.twig' %}
{% block title %}About Us{% endblock %}

{% block body %}
<div class="span9">
    <div class="page-header">
        <h1>1. About</h1>
    </div>
    <p class="lead">In order to better understand what a framework is, let’s leave the world of computer science for a moment and imagine a mountaineering adventure. Developing an application is very similar to climbing a rock wall: you are at the bottom (you have an application to be created) and you need to reach the summit (and be pleased with the achievement of designing an application that works perfectly.)</p>
    <p class="lead">In order to better understand what a framework is, let’s leave the world of computer science for a moment and imagine a mountaineering adventure. Developing an application is very similar to climbing a rock wall: you are at the bottom (you have an application to be created) and you need to reach the summit (and be pleased with the achievement of designing an application that works perfectly.)</p>
    <p class="lead">In order to better understand what a framework is, let’s leave the world of computer science for a moment and imagine a mountaineering adventure. Developing an application is very similar to climbing a rock wall: you are at the bottom (you have an application to be created) and you need to reach the summit (and be pleased with the achievement of designing an application that works perfectly.)</p>

</div><!--/span-->
{% endblock %}


{% block javascripts %}
{{parent()}}
<script>
  $(document).ready(function(){
      //add active class for about nav link
      $('#aboutLink').addClass('active');
  });
</script>    
{% endblock %}

src/Iti/BlogBundle/Resources/views/Blog/category.html.twig
{% extends '::base.html.twig' %}
{% block title %}{{category.name}}{% endblock %}

{% block body %}

<div class="span9">
    <h2>{{category.name}} posts</h2>
    <div class="row-fluid">
        <ul class="thumbnails">
            {% for latestPost in posts %}
                <li class="span4">
                    <div class="thumbnail">
                        <img src="{{latestPost.getWebPath()}}" width="300" height="200" alt="">
                        <div class="caption">
                            <h3>{{latestPost.title}}</h3>
                            <p>{{latestPost.content}}</p>
                            <p><a href="{{path('post_show',{'id' : latestPost.id})}}" class="btn btn-primary">more</a></p>
                        </div>
                    </div>
                </li>
            {% else %}

            {% endfor %}
            </ul>
        </div>
        <div class="pagination pagination-centered">
            {% if lastPageNumber > 1 %}
                <ul>
                    {% if page > 1 %}
                                                                <li><a href="{{ url('category',{'id' : id }) }}">First</a></li>
                                                                <li><a href="{{ url('category', { 'id' : id,'page': page - 1}) }}">Prev</a></li>
                    {% endif %}

        {% for numberOfPage in 1..lastPageNumber %}
        {% if numberOfPage > page - 3 and numberOfPage < page + 3 %}
                                {% if page == numberOfPage %}<li class="active"><a href="#">{{ numberOfPage }}</a></li>{% else %}<li><a href="{{ url('category', {'id' : id,'page': numberOfPage}) }}">{{ numberOfPage }}</a></li>{%endif%}
        {% endif %}
        {% endfor %}


                    {% if page < lastPageNumber %}
                                                                <li><a href="{{ url('category', {'id' : id,'page': page + 1}) }}">Next</a></li>
                                                                <li><a href="{{ url('category', {'id' : id,'page': lastPageNumber}) }}">Last</a></li>                    
{% endif %}
                                                                </ul>
                {% endif %}
        </div>
    </div><!--/span-->


{% endblock %}

{% block javascripts %}
{{parent()}}
    <script>
      $(document).ready(function(){
          //add active class for home nav link
          $('#homeLink').addClass('active');
      });
        </script>    
{% endblock %}

src/Iti/BlogBundle/Resources/views/Blog/index.html.twig
{% extends '::base.html.twig' %}

{% block body %}

<div class="span9">
    <h2>Recent posts</h2>
    <div class="row-fluid">
        <ul class="thumbnails">
            {% for latestPost in latestPosts %}
                <li class="span4">
                    <div class="thumbnail">
                        <img src="{{latestPost.getWebPath()}}" width="300" height="200" alt="">
                        <div class="caption">
                            <h3>{{latestPost.title}}</h3>
                            <p>{{latestPost.content}}</p>
                            <p><a href="{{path('post_show',{'id' : latestPost.id})}}" class="btn btn-primary">more</a></p>
                        </div>
                    </div>
                </li>
            {% else %}

            {% endfor %}
            </ul>
        </div>
    </div><!--/span-->


{% endblock %}

{% block javascripts %}
{{parent()}}
    <script>
      $(document).ready(function(){
          //add active class for home nav link
          $('#homeLink').addClass('active');
      });
        </script>    
{% endblock %}

src/Iti/BlogBundle/Resources/views/Blog/newComment.html.twig
<hr class="bs-docs-separator">
<h3>{{comment.createdAt|date('d/m/Y h:i A')}}</h3>
<p>{{comment.comment}}</p>

src/Iti/BlogBundle/Resources/views/Blog/sideBar.html.twig
<div class="affix">
    <h3>Categories</h3>
    <ul class="nav nav-list">
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
    </ul>
    <h3>Most viewed</h3>
    <ul class="nav nav-list">
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
    </ul>
    <h3>Most commented</h3>
    <ul class="nav nav-list">
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
    </ul>
</div>

src/Iti/BlogBundle/Resources/views/Blog/tag.html.twig
{% extends '::base.html.twig' %}
{% block title %}{{tag.name}}{% endblock %}

{% block body %}

<div class="span9">
    <h2>{{tag.name}} posts</h2>
    <div class="row-fluid">
        <ul class="thumbnails">
            {% for latestPost in posts %}
                <li class="span4">
                    <div class="thumbnail">
                        <img src="{{latestPost.getWebPath()}}" width="300" height="200" alt="">
                        <div class="caption">
                            <h3>{{latestPost.title}}</h3>
                            <p>{{latestPost.content}}</p>
                            <p><a href="{{path('post_show',{'id' : latestPost.id})}}" class="btn btn-primary">more</a></p>
                        </div>
                    </div>
                </li>
            {% else %}

            {% endfor %}
            </ul>
        </div>
        <div class="pagination pagination-centered">
            {% if lastPageNumber > 1 %}
                <ul>
                    {% if page > 1 %}
                                                                <li><a href="{{ url('tags',{'id' : id }) }}">First</a></li>
                                                                <li><a href="{{ url('tags', { 'id' : id,'page': page - 1}) }}">Prev</a></li>
                    {% endif %}

        {% for numberOfPage in 1..lastPageNumber %}
        {% if numberOfPage > page - 3 and numberOfPage < page + 3 %}
                                {% if page == numberOfPage %}<li class="active"><a href="#">{{ numberOfPage }}</a></li>{% else %}<li><a href="{{ url('tags', {'id' : id,'page': numberOfPage}) }}">{{ numberOfPage }}</a></li>{%endif%}
        {% endif %}
        {% endfor %}


                    {% if page < lastPageNumber %}
                                                                <li><a href="{{ url('tags', {'id' : id,'page': page + 1}) }}">Next</a></li>
                                                                <li><a href="{{ url('tags', {'id' : id,'page': lastPageNumber}) }}">Last</a></li>                    
{% endif %}
                                                                </ul>
                {% endif %}
        </div>
    </div><!--/span-->


{% endblock %}

{% block javascripts %}
{{parent()}}
    <script>
      $(document).ready(function(){
          //add active class for home nav link
          $('#homeLink').addClass('active');
      });
        </script>    
{% endblock %}